kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-0807-02-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: test-0807-02-dsp-job
    namespace: rhdh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-0807-02-dsp-job-role